services:
  redis:
    image: redis
    restart: always

  postgres:
    image: postgres:13.0
    environment:
       - POSTGRES_USER=${POSTGRES_USER}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - default

  outline:
    image: outlinewiki/outline:latest
    container_name: outline
    command: sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DATABASE_URL_TEST=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}-test
      - REDIS_URL=redis://redis:6379
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env_outline
    networks:
      - default
      - public_ingress

networks:
  public_ingress:
    name: public_ingress
    external: true
