services:
  db:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_POST: 5432
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HOSTNAME_STRICT: true
      KC_PROXY: edge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    env_file:
      - .env_keycloak
    command: ["start"]
    networks:
      - public_ingress
      - default
    volumes:
      - ./providers:/opt/keycloak/providers
    depends_on:
      db:
        condition: service_healthy

networks:
  public_ingress:
    name: public_ingress
    external: true